/*
 * generated by Xtext
 */
package org.xtext.fofo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ApricotRuntimeModule extends org.xtext.fofo.AbstractApricotRuntimeModule {

}
