/**
 * generated by Xtext
 */
package org.xtext.fofo.validation;

import org.xtext.fofo.validation.AbstractApricotValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ApricotValidator extends AbstractApricotValidator {
}
