/*
 * generated by Xtext
 */
package org.xtext.fofo.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.fofo.ui.internal.ApricotActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ApricotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ApricotActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ApricotActivator.getInstance().getInjector(ApricotActivator.ORG_XTEXT_FOFO_APRICOT);
	}
	
}
