/**
 * generated by Xtext
 */
package org.xtext.fofo.ui.contentassist;

import org.xtext.fofo.ui.contentassist.AbstractApricotProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ApricotProposalProvider extends AbstractApricotProposalProvider {
}
