/*
* generated by Xtext
*/
package org.xtext.fofo;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ApricotUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.fofo.ui.internal.ApricotActivator.getInstance().getInjector("org.xtext.fofo.Apricot");
	}
	
}
