/*
 * generated by Xtext
 */
package org.xtext.fofo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ApricotUiModule extends org.xtext.fofo.ui.AbstractApricotUiModule {
	public ApricotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
